import { mkdirSync, writeFileSync, readdirSync, rmSync, existsSync } from 'node:fs';
import { join, dirname, resolve as resolvePath } from 'node:path';
import { resolveIndexPath, openIndex, getAllNodes, getAllEdges } from './db.mjs';
import { renderMermaidFlowchart } from './render.mjs';

const DEFAULT_BANNER = '> Generated by graphwright wiki — do not hand-edit. Regenerate: `{cmd}`';
const WIKI_EDGE_KINDS = ['imports', 'calls'];
const TOP_EXPORTED_LIMIT = 5;
const NON_SYMBOL_KINDS = new Set(['file', 'import']);

function groupForPath(filePath, depth) {
  const parts = filePath.split('/');
  parts.pop();
  const truncated = parts.slice(0, Math.max(0, depth));
  return truncated.length === 0 ? '.' : truncated.join('/');
}

function groupPageRelPath(group) {
  return group === '.' ? 'root.md' : `${group}.md`;
}

function escapeMd(s) {
  return String(s ?? '').replace(/\|/g, '\\|').replace(/\r?\n/g, ' ');
}

function renderBanner(template, cmd) {
  let text = template.replaceAll('{cmd}', cmd);
  if (text.includes('{date}')) {
    text = text.replaceAll('{date}', new Date().toISOString().slice(0, 10));
  }
  return text;
}

function firstDocLine(docstring) {
  if (!docstring) return '';
  return docstring.split('\n')[0].trim();
}

function walkMdFiles(dir, baseDir = dir) {
  if (!existsSync(dir)) return [];
  const out = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) {
      out.push(...walkMdFiles(full, baseDir));
    } else if (entry.isFile() && entry.name.endsWith('.md')) {
      out.push(full.slice(baseDir.length + 1).split('\\').join('/'));
    }
  }
  return out;
}

function removeEmptyDirs(dir, baseDir = dir) {
  if (!existsSync(dir)) return;
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    if (entry.isDirectory()) removeEmptyDirs(join(dir, entry.name), baseDir);
  }
  if (dir !== baseDir && readdirSync(dir).length === 0) {
    rmSync(dir, { recursive: true });
  }
}

function buildIndexPage(bannerText, groupNames, groupStats) {
  const lines = [bannerText, '', '# Codegraph Wiki', '', '| Group | Files | Symbols | Top exported symbols |', '| --- | --- | --- | --- |'];
  for (const g of groupNames) {
    const stats = groupStats.get(g);
    const link = `[${escapeMd(g)}](${groupPageRelPath(g)})`;
    lines.push(`| ${link} | ${stats.fileCount} | ${stats.symbolCount} | ${escapeMd(stats.topExported.join(', '))} |`);
  }
  return lines.join('\n') + '\n';
}

function buildGroupPage(bannerText, group, groupNodes, nodeGroup, nodesById, allWikiEdges, maxDiagramEdges) {
  const lines = [bannerText, '', `# ${group}`, ''];

  lines.push('## Exported symbols', '');
  const exported = groupNodes.filter((n) => n.is_exported === 1);
  if (exported.length === 0) {
    lines.push('None.', '');
  } else {
    lines.push('| Name | Kind | Location | Doc |', '| --- | --- | --- | --- |');
    for (const n of exported) {
      lines.push(
        `| ${escapeMd(n.name)} | ${escapeMd(n.kind)} | ${escapeMd(n.file_path)}:${n.start_line} | ${escapeMd(firstDocLine(n.docstring))} |`
      );
    }
    lines.push('');
  }

  const intraEdgeMap = new Map();
  for (const e of allWikiEdges) {
    if (nodeGroup.get(e.source) !== group || nodeGroup.get(e.target) !== group) continue;
    const sf = nodesById.get(e.source)?.file_path;
    const tf = nodesById.get(e.target)?.file_path;
    if (!sf || !tf || sf === tf) continue;
    const key = `${sf}\u0000${tf}`;
    if (!intraEdgeMap.has(key)) intraEdgeMap.set(key, { source: sf, target: tf, kinds: new Set() });
    intraEdgeMap.get(key).kinds.add(e.kind);
  }
  const intraEdges = [...intraEdgeMap.values()].sort((a, b) =>
    a.source < b.source ? -1 : a.source > b.source ? 1 : a.target < b.target ? -1 : a.target > b.target ? 1 : 0
  );

  lines.push('## Diagram', '');
  if (intraEdges.length === 0) {
    lines.push('No intra-group dependencies.', '');
  } else if (intraEdges.length > maxDiagramEdges) {
    lines.push(`Too many intra-group edges (${intraEdges.length}) for a diagram — plain edge list:`, '');
    for (const e of intraEdges) {
      lines.push(`- \`${e.source}\` → \`${e.target}\` (${[...e.kinds].sort().join(', ')})`);
    }
    lines.push('');
  } else {
    const fileIds = [...new Set(intraEdges.flatMap((e) => [e.source, e.target]))].sort();
    const mermaidNodes = fileIds.map((f) => ({ id: f, label: f }));
    const mermaidEdges = intraEdges.map((e) => ({ source: e.source, target: e.target, label: [...e.kinds].sort().join(',') }));
    const { text } = renderMermaidFlowchart(mermaidNodes, mermaidEdges, { cap: maxDiagramEdges });
    lines.push('```mermaid', text.trimEnd(), '```', '');
  }

  const crossCounts = new Map();
  for (const e of allWikiEdges) {
    if (nodeGroup.get(e.source) !== group) continue;
    const targetGroup = nodeGroup.get(e.target);
    if (targetGroup == null || targetGroup === group) continue;
    crossCounts.set(targetGroup, (crossCounts.get(targetGroup) ?? 0) + 1);
  }
  lines.push('## Cross-group dependencies', '');
  if (crossCounts.size === 0) {
    lines.push('None.', '');
  } else {
    for (const targetGroup of [...crossCounts.keys()].sort()) {
      lines.push(`- ${group} → ${targetGroup} (${crossCounts.get(targetGroup)})`);
    }
    lines.push('');
  }

  return lines.join('\n') + '\n';
}

/**
 * Run `graphwright wiki`. Options are already validated/typed by the CLI
 * layer. Returns a process exit code; never throws.
 */
export function runWiki({ out, groupDepth, banner, maxDiagramEdges, project, cmd }, { cwd, stdout, stderr }) {
  const resolved = resolveIndexPath({ cwd, project });
  if (resolved.error) {
    stderr.write(resolved.error + '\n');
    return resolved.code;
  }

  let db;
  let warning;
  try {
    ({ db, warning } = openIndex(resolved.path));
  } catch (err) {
    stderr.write(err.message + '\n');
    return err.code ?? 1;
  }
  if (warning) stderr.write(`warning: ${warning}\n`);

  const allNodes = getAllNodes(db);
  const wikiEdges = getAllEdges(db, WIKI_EDGE_KINDS);
  const nodesById = new Map(allNodes.map((n) => [n.id, n]));

  const groups = new Map();
  const nodeGroup = new Map();
  for (const n of allNodes) {
    const g = groupForPath(n.file_path, groupDepth);
    nodeGroup.set(n.id, g);
    if (!groups.has(g)) groups.set(g, []);
    groups.get(g).push(n);
  }
  const groupNames = [...groups.keys()].sort();

  const groupStats = new Map();
  for (const g of groupNames) {
    const nodes = groups.get(g);
    const files = new Set(nodes.map((n) => n.file_path));
    const symbols = nodes.filter((n) => !NON_SYMBOL_KINDS.has(n.kind));
    const topExported = nodes
      .filter((n) => n.is_exported === 1)
      .map((n) => n.name)
      .sort()
      .filter((v, i, arr) => arr.indexOf(v) === i)
      .slice(0, TOP_EXPORTED_LIMIT);
    groupStats.set(g, { fileCount: files.size, symbolCount: symbols.length, topExported });
  }

  const bannerText = renderBanner(banner ?? DEFAULT_BANNER, cmd);

  const outDir = resolvePath(cwd, out);
  mkdirSync(outDir, { recursive: true });

  const expected = new Set(['index.md', ...groupNames.map(groupPageRelPath)]);
  const existing = walkMdFiles(outDir);
  for (const rel of existing) {
    if (!expected.has(rel)) rmSync(join(outDir, rel));
  }
  removeEmptyDirs(outDir);

  writeFileSync(join(outDir, 'index.md'), buildIndexPage(bannerText, groupNames, groupStats), 'utf8');
  for (const g of groupNames) {
    const rel = groupPageRelPath(g);
    const full = join(outDir, rel);
    mkdirSync(dirname(full), { recursive: true });
    const content = buildGroupPage(bannerText, g, groups.get(g), nodeGroup, nodesById, wikiEdges, maxDiagramEdges);
    writeFileSync(full, content, 'utf8');
  }

  stdout.write(`Wrote wiki (${groupNames.length} group${groupNames.length === 1 ? '' : 's'}) to ${outDir}\n`);
  return 0;
}
